# Generated by Django 4.2.3 on 2023-07-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('email', models.CharField(max_length=150, verbose_name='почта')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='время рассылки')),
                ('last_sent', models.DateTimeField(blank=True, default=None, null=True, verbose_name='время последней отправки')),
                ('finish_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='время окончания рассылки')),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='время начала рассылки')),
                ('interval', models.CharField(choices=[('раз/день', 'раз/день'), ('раз/неделя', 'раз/неделя'), ('раз/месяц', 'раз/месяц')], verbose_name='периодичность')),
                ('status', models.CharField(choices=[('завершена', 'завершена'), ('создана', 'создана'), ('запущена', 'запущена')], default='создана', verbose_name='статус рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('status',),
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='дата и время')),
                ('attempt', models.BooleanField(default=True, verbose_name='статус попытки')),
                ('server_response', models.BooleanField(default=True, verbose_name='ответ сервера')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
                'ordering': ('server_response',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150, verbose_name='тема')),
                ('contents', models.TextField(verbose_name='содержание')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('header',),
            },
        ),
    ]
