# Generated by Django 4.2.3 on 2023-07-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='header',
            field=models.CharField(max_length=150, verbose_name='тема'),
        ),
        migrations.AlterField(
            model_name='message',
            name='header',
            field=models.CharField(max_length=150, verbose_name='тема'),
        ),
    ]
